name: alt_http
version: 0.1.0
description: Patched original Dart HttpClient to allow case sensitive headers.
author: shaxxx <developer@krkadoni.com>
homepage: https://github.com/shaxxx/AltHttp

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:

dev_dependencies:
  test: ^1.6.8